---  
- name: install packages
  become: yes
  apt:
    name:
      - xserver-xorg
      - lightdm
      - lxde-core
      
- name: copy lightdm config file
  become: yes
  copy:
    src: etc/lightdm/lightdm.conf
    dest: /etc/lightdm/lightdm.conf
    owner: root
    group: root
  notify: restart lightdm