---  
- name: install packages
  become: yes
  apt:
    name:
      - xserver-xorg
      - lightdm
      - lxde-core
      
- name: copy lightdm config file
  become: yes
  copy:
    src: etc/lightdm/lightdm.conf
    dest: /etc/lightdm/lightdm.conf
    owner: root
    group: root
  notify: restart lightdm
  
- name: copy lxde startup config file
  become: yes
  copy:
    src: home/goldo/.config/lxsession/LXDE/autostart
    dest: /home/goldo/.config/lxsession/LXDE/autostart
    owner: goldo
    group: goldo
  notify: restart lightdm