stages:
  - deploy
    
provision:
  stage: deploy
  when: manual
  tags:
    - ansible
  script:
    - ansible-playbook -i hosts provision_raspberrypi.yml
    
base:
  stage: deploy
  when: manual
  tags:
    - ansible
  script:
    - ansible-playbook -i hosts base.yml    

gui:
  stage: deploy
  when: manual
  tags:
    - ansible
  script:
    - ansible-playbook -i hosts gui.yml

nucleo_comm_uart:
  stage: deploy
  when: manual
  tags:
    - ansible
  script:
    - ansible-playbook -i hosts nucleo_comm_uart.yml
    
nucleo_openocd:
  stage: deploy
  when: manual
  tags:
    - ansible
  script:
    - ansible-playbook -i hosts nucleo_openocd.yml
    
samba_share:
  stage: deploy
  when: manual
  tags:
    - ansible
  script:
    - ansible-playbook -i hosts samba_share.yml
