stages:
  - deploy
    
provision:
  stage: deploy
  when: manual
  tags:
    - ansible
  script:
    - ansible-playbook -i hosts provision_raspberrypi.yml
    
base:
  stage: deploy
  when: manual
  tags:
    - ansible
  script:
    - ansible-playbook -i hosts base.yml
    
ros:
  stage: deploy
  when: manual
  tags:
    - ansible
  script:
    - ansible-playbook -i hosts ros.yml

gui:
  stage: deploy
  when: manual
  tags:
    - ansible
  script:
    - ansible-playbook -i hosts gui.yml
    
openocd-stm32:
  stage: deploy
  when: manual
  tags:
    - ansible
  script:
    - ansible-playbook -i hosts openocd-stm32.yml
    