stages:
  - deploy
    
provision:
  stage: deploy
  when: manual
  tags:
    - ansible
  script:
    - ansible-playbook -i hosts provision_raspberrypi.yml
    
base:
  stage: deploy
  when: manual
  tags:
    - ansible
  script:
    - ansible-playbook -i hosts base.yml
    
install_ros:
  stage: deploy
  when: manual
  tags:
    - ansible
  script:
    - ansible-playbook -i hosts install_ros.yml
