# File: provision_raspberrypi.yml
---
- name: reset host key
  hosts: robots
  connection: local
  tasks:
  - name: remove existing key
    known_hosts:
      name: "{{ inventory_hostname }}"
      state: absent

- hosts: robots
  vars:
  - ansible_user: pi
  - ansible_ssh_pass: raspberry
  - ansible_password: raspberry
  - ansible_become_password: raspberry
  roles:
  - provision
  
- hosts: robots 
  vars:
  - ansible_user: ansible
  roles:
  - base