# File: provision_raspberrypi.yml
---
- name: reset host key
  hosts: robots
  connection: local
  tasks:
  - name: remove existing key
    known_hosts:
      name: "{{ inventory_hostname }}"
      state: absent

- hosts: robots
  vars:
  - ansible_ssh_extra_args: '-o StrictHostKeyChecking=no'
  - provision_ansible_password: "{{ ansible_become_password }}"
  - ansible_user: "{{ provision_user }}"
  - ansible_ssh_pass: "{{ provision_password }}"
  - ansible_password: "{{ provision_password }}"
  - ansible_become_password: "{{ provision_password }}"
  roles:
  - provision
