---
- name: create ansible user
  become: yes
  user:
    name: ansible
    append: yes
    groups:
      - sudo
    password: "{{provision_ansible_password | password_hash('sha512')}}"
    shell: /bin/bash

- name: set ansible user ssh key
  become: yes
  authorized_key:
    exclusive: yes
    user: ansible
    key: "{{ lookup('file', '~/.ssh/id_ed25519.pub') }}"
