---
- name: restart wifi
  become: yes
  shell: |
    rfkill unblock 0
    wpa_cli -i wlan0 reconfigure
    
- name: restart udev
  become: yes
  shell: |
    udevadm control --reload-rules
    udevadm trigger