---  
- name: install packages
  become: yes
  apt:
    name:
      - xserver-xorg
      - lightdm
      - lxde-core
      - unclutter
      
- name: copy lightdm config file
  become: yes
  template:
    src: etc/lightdm/lightdm.conf
    dest: /etc/lightdm/lightdm.conf
  notify: restart lightdm
  
- name: create lxde startup directory
  become: yes
  file:
    path: /home/{{robot_user}}/.config/lxsession/LXDE
    state: directory
    owner: "{{robot_user}}"
    group: "{{robot_user_group}}"
