---
- name: add ros apt-key
  become: yes
  apt_key:
    id: C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654
    keyserver:  hkp://keyserver.ubuntu.com:80
    state: present
    
- name: add ros repository
  become: yes
  apt_repository:
    repo: "deb http://packages.ros.org/ros/ubuntu buster main"
    state: present
    filename: ros.list
    update_cache: yes
    
- name: install ros bootstrap packages
  become: yes
  apt:
    name:
      - python-rosdep
      - python-rosinstall-generator
      - python-wstool
      - python-rosinstall
      - build-essential
