---
- name: add ros apt-key
  become: yes
  apt_key:
    id: C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654
    keyserver:  hkp://keyserver.ubuntu.com:80
    state: present
    
- name: add ros repository
  become: yes
  apt_repository:
    repo: "deb http://packages.ros.org/ros/ubuntu buster main"
    state: present
    filename: ros.list
    update_cache: yes
    
- name: install ros bootstrap packages
  become: yes
  apt:
    name:
      - python-rosdep
      - python-rosinstall-generator
      - python-wstool
      - python-rosinstall
      - build-essential
      
- name: check if rosdep init is needed
  stat:
    path: /etc/ros/rosdep/sources.list.d/20-default.list
  register: stat_result
  
- name: init rosdep
  when: stat_result.stat.exists == False
  become: yes
  shell:
    cmd: rosdep init

- name: update rosdep
  shell:
    cmd: rosdep update

- name: create catkin workspace directory
  file:
    path: ~/ros_catkin_ws
    state: directory
    
- name: generate rosinstall file
  shell:
    chdir: ~/ros_catkin_ws
    cmd: rosinstall_generator ros_comm --rosdistro melodic --deps --tar > melodic-ros_comm.rosinstall
    
- name: fetch core packages
  shell:
    chdir: ~/ros_catkin_ws
    cmd: wstool init -j8 src melodic-ros_comm.rosinstall
    
- name: install dependencies
  shell:
    chdir: ~/ros_catkin_ws
    cmd: rosdep install --from-paths src --ignore-src --rosdistro melodic -y
    
- name: build ros
  shell:
    chdir: ~/ros_catkin_ws
    cmd: ./src/catkin/bin/catkin_make_isolated --install -DCMAKE_BUILD_TYPE=Release --install-space /opt/ros/melodic