--- 
- name: set hostname
  become: yes
  hostname:
    name: "{{inventory_hostname}}"
    
- name: set hosts file
  become: yes
  template:
    src: etc/hosts
    dest: /etc/hosts
    owner: root
    group: root
    mode: preserve
    
- name: copy root ca
  become: yes
  copy:
    src: ThomasLiennardRootCA.crt
    dest: /usr/local/share/ca-certificates/
    owner: root
    group: root
    mode: '0644'
  notify: update ca-certificates
    
- name: create local user
  become: yes
  user:
    name: goldo
    append: yes
    groups:
      - sudo
    password: $6$lECLv9cU$gvx45ic2ouNR7UNjpcnvV4KSEPQg7GRryn3dziCToBl82Qrczw1P17KwwLpVbQXaWUFTOO5k/Jpa6lOTXN5Ak.
    shell: /bin/bash
    
- name: set local user ssh key
  become: yes
  authorized_key:
    exclusive: yes
    user: goldo
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPgjBGCCUdKua2Fmf8llaWuQq/ZcmvdwirS8aCBWuupW lab\\thomas@DESKTOP-53RG1OH \n ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFEkQWNaQeCqYC+f1MKo48IiDEIPL5RnApE8HTUJBhuZ webssh@lab.thomas-liennard.fr"

- name: remove pi user
  become: yes
  user:
    name: pi
    state: absent