--- 
- name: set hostname
  become: yes
  hostname:
    name: "{{inventory_hostname}}"
    
- name: set hosts file
  become: yes
  template:
    src: etc/hosts
    dest: /etc/hosts
    owner: root
    group: root
    mode: preserve
    
- name: copy root ca
  become: yes
  copy:
    src: ThomasLiennardRootCA.crt
    dest: /usr/local/share/ca-certificates/
    owner: root
    group: root
    mode: '0644'
  notify: update ca-certificates
    
- name: create local user
  become: yes
  user:
    name: goldo
    append: yes
    groups:
      - sudo
    password: "{{ansible_become_password | password_hash('sha512')}}"
    shell: /bin/bash
    
- name: set local user ssh key
  become: yes
  authorized_key:
    exclusive: yes
    user: goldo
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPgjBGCCUdKua2Fmf8llaWuQq/ZcmvdwirS8aCBWuupW lab\\thomas@DESKTOP-53RG1OH"

- name: install git
  become: yes
  package:
    name:
      - git
    
- name: configure git credentials helper
  command:
    cmd: git config --global credential.helper store
    
- name: configure git username
  command:
    cmd: git config --global credential.https://gitlab.lab.thomas-liennard.fr.username thomas

    
- name: update all packages
  become: yes
  apt:
    upgrade: dist
    update_cache: yes
    cache_valid_time: 3600
    