---
- name: set hostname
  become: yes
  hostname:
    name: "{{inventory_hostname}}"

- name: set hosts file
  become: yes
  template:
    src: etc/hosts
    dest: /etc/hosts
    owner: root
    group: root
    mode: preserve

- name: create local user
  become: yes
  user:
    name: "{{ robot_user }}"
    append: yes
    groups:
      - sudo
    password: "{{robot_user_password | password_hash('sha512')}}"
    shell: /bin/bash

- name: set local user ssh key
  become: yes
  authorized_key:
    user: "{{ robot_user }}"
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPgjBGCCUdKua2Fmf8llaWuQq/ZcmvdwirS8aCBWuupW lab\\thomas@DESKTOP-53RG1OH"

- name: update all packages
  become: yes
  apt:
    upgrade: dist
    update_cache: yes
    cache_valid_time: 3600

- name: install essential packages
  become: yes
  package:
    name:
      - git
      - build-essential
      - cmake
      - python3

- name: create workspace directory
  become: yes
  file:
    path: "{{ robot_workspace_path }}"
    state: directory
    owner: "{{ robot_user }}"
    group: "{{ robot_user_group }}"
