--- 
- name: set hostname
  become: yes
  hostname:
    name: "{{inventory_hostname}}"

- name: set hosts file
  become: yes
  template:
    src: etc/hosts
    dest: /etc/hosts
    owner: root
    group: root
    mode: preserve
    
- name: set wpa_supplicant config file
  become: yes
  template:
    src: etc/wpa_supplicant/wpa_supplicant.conf
    dest: /etc/wpa_supplicant/wpa_supplicant.conf
    owner: root
    group: root
    mode: preserve
  notify: restart wifi
  
- name: set dhcpcd config file
  become: yes
  template:
    src: etc/dhcpcd.conf
    dest: /etc/dhcpcd.conf
    owner: root
    group: root
    mode: preserve
  notify: restart wifi

- name: create local user
  become: yes
  user:
    name: "{{ robot_user }}"
    append: yes
    groups:
      - sudo
    password: "{{robot_user_password | password_hash('sha512')}}"
    shell: /bin/bash    

- name: set local user ssh key
  become: yes
  authorized_key:
    user: "{{ robot_user }}"
    key: "{{ item }}"
  loop: "{{robot_user_ssh_keys}}"  
- name: delete default user
  become: yes
  user:
    name: pi
    state: absent
    remove: yes
    
- name: update all packages
  become: yes
  apt:
    upgrade: dist
    update_cache: yes
    cache_valid_time: 3600

- name: install essential packages
  become: yes
  package:
    name:
      - git
      - build-essential
      - cmake
      - python3

- name: create workspace directory
  become: yes
  file:
    path: "{{ robot_workspace_path }}"
    state: directory
    owner: "{{ robot_user }}"
    group: "{{ robot_user_group }}"
    
- name: create devices directory
  become: yes
  file:
    path: /dev/goldorak
    state: directory
    
- name: set udev config file
  become: yes
  template:
    src: etc/udev/rules.d/99-usb-serial.rules
    dest: /etc/udev/rules.d/99-usb-serial.rules
    owner: root
    group: root
  notify: restart udev
